"""Sky events, journal posts and gallery photographs."""

# ---------------------------------------------------------------- sky events
# schedule row: (time, activity, open_to_public)
EVENTS = [
    dict(title="Orionid Meteor Shower Peak", type="meteor_shower", start="2026-10-20", end="2026-10-22", vis=7, kp=3, stream=True, color="#ffd166", exp="cabin",
         tip="Lie on your back facing south-east after midnight. Give your eyes twenty minutes to adapt and do not look at your phone.",
         body="<p>Debris from Halley's comet hits the atmosphere at 66 kilometres per second, producing fast, bright meteors that often leave glowing trains. Our dark-sky field is a perfect place to watch.</p>",
         schedule=[("22:00", "Hot drinks and introductions", True), ("23:30", "Guided meteor count", True), ("02:00", "Long-exposure session", False)], art=dict(palette="solar", motif="pines", seed=41)),
    dict(title="Harvest Moon Aurora Festival", type="festival", start="2026-10-31", end="2026-11-02", vis=6, kp=4, stream=True, color="#b388ff", exp="skystation",
         tip="Dress in layers and bring a flask. The festival field is open all night and has a warming tent with live music.",
         body="<p>Three nights of music, storytelling and sky-watching at the station. Local musicians play in the warming tent between aurora alerts, and Mikkel tells the old tales by the fire.</p>",
         schedule=[("18:00", "Opening soup supper", True), ("20:00", "Fire-side stories with Mikkel", True), ("22:30", "Live music in the warming tent", True), ("00:00", "Aurora watch", True)], art=dict(palette="violet", motif="tent", seed=42)),
    dict(title="Leonid Meteor Shower", type="meteor_shower", start="2026-11-16", end="2026-11-18", vis=6, kp=3, stream=False, color="#ff80ab", exp="iceland",
         tip="The Leonids peak before dawn. Set an alarm for 4 a.m. and watch from a spot that faces east.",
         body="<p>A modest but dependable shower with swift, bright meteors. Every thirty-three years the Leonids become a storm; this is not one of those years, but we will watch anyway.</p>",
         schedule=[("03:30", "Pre-dawn coffee", True), ("04:00", "Guided meteor count", True)], art=dict(palette="crimson", motif="ice", seed=43)),
    dict(title="Comet Halvorsen-Vale (C/2026 X1)", type="comet", start="2026-11-28", end="2026-12-09", vis=8, kp=2, stream=True, color="#22d3ee", exp="skystation",
         tip="The comet will be low in the west after sunset. Bring binoculars and find a horizon with no trees.",
         body="<p>Discovered by two amateur astronomers earlier this year, this long-period comet may reach naked-eye brightness in early December. We will host nightly viewing sessions with the Norn 40 cm reflector.</p>",
         schedule=[("17:00", "Telescope queue opens", True), ("18:30", "Comet talk with Amara", True), ("20:00", "Astrophotography session", False)], art=dict(palette="glacier", motif="dome", seed=44)),
    dict(title="Geomagnetic Storm Watch: Solar Cycle Surge", type="storm_watch", start="2026-12-02", end="2026-12-04", vis=10, kp=8, stream=True, color="#37ffb0", exp="fjord",
         tip="When a storm watch is issued, the station sends alerts to everyone on the guest list. Keep your phone charged and your boots by the door.",
         body="<p>A large coronal hole is rotating to face Earth, and the forecast desk expects G3 storm conditions. Expect the aurora to be visible far south of its normal oval. This is a watch, not a promise, but it is the one we have been waiting for.</p>",
         schedule=[("20:00", "Forecast briefing", True), ("22:00", "Storm-watch vigil begins", True), ("03:00", "Debrief over soup", True)], art=dict(palette="emerald", motif="pines", seed=45)),
    dict(title="Geminid Meteor Shower", type="meteor_shower", start="2026-12-13", end="2026-12-14", vis=9, kp=3, stream=True, color="#ffd166", exp="svalbard",
         tip="The Geminids are the year's best shower. Yellow-white, slow and plentiful. Look in any direction.",
         body="<p>Up to 120 meteors per hour from the asteroid 3200 Phaethon. Because Svalbard is in polar night, the whole evening is dark enough to watch.</p>",
         schedule=[("21:00", "Dinner and briefing", True), ("22:30", "Watch begins", True)], art=dict(palette="solar", motif="ice", seed=46)),
    dict(title="Winter Solstice Vigil", type="solstice", start="2026-12-21", end="2026-12-22", vis=7, kp=4, stream=True, color="#82b1ff", exp="midnight",
         tip="Expect a long night. We light a fire at dusk and keep it burning until the light returns.",
         body="<p>The longest night of the year, observed the old way: a fire, a pot of soup and everyone outside until dawn. If the aurora appears, nobody will sleep anyway.</p>",
         schedule=[("15:30", "Fire lit", True), ("18:00", "Solstice supper", True), ("21:00", "Stories and songs", True), ("07:00", "Sunrise toast", True)], art=dict(palette="royal", motif="cabin", seed=47)),
    dict(title="Quadrantid Meteor Shower", type="meteor_shower", start="2027-01-03", end="2027-01-04", vis=7, kp=3, stream=False, color="#69f0ae", exp="brooks",
         tip="The Quadrantids have a narrow peak, only a few hours long. Check the exact peak time in our morning briefing.",
         body="<p>A short, sharp shower that can produce over 100 meteors per hour at its peak. Famous for bright fireballs.</p>",
         schedule=[("04:00", "Coffee and briefing", True)], art=dict(palette="emerald", motif="tent", seed=48)),
    dict(title="Ice Lab Open Night", type="festival", start="2027-01-22", end="2027-01-22", vis=5, kp=3, stream=False, color="#22d3ee", exp="skystation",
         tip="Bring questions. The staff are in a good mood and the hot chocolate is unlimited.",
         body="<p>Once a winter we open every instrument hut to the public. See the magnetometer, peek through the spectrograph, and watch the Hugin laser fire into the night.</p>",
         schedule=[("18:00", "Doors open", True), ("19:00", "Instrument tours", True), ("21:00", "Hugin laser demonstration", True)], art=dict(palette="glacier", motif="dome", seed=49)),
    dict(title="Deep Winter Storm Window", type="storm_watch", start="2027-02-09", end="2027-02-11", vis=9, kp=7, stream=True, color="#ff5c8a", exp="greenland",
         tip="Storm windows are based on the solar cycle, not a specific flare. Stay flexible.",
         body="<p>A statistically favoured window for strong storms, based on the last two solar cycles. We will keep the forecast desk open around the clock.</p>",
         schedule=[("All night", "Forecast desk open to visitors", True)], art=dict(palette="crimson", motif="pines", seed=50)),
    dict(title="Spring Equinox Aurora Peak", type="equinox", start="2027-03-18", end="2027-03-22", vis=10, kp=6, stream=True, color="#37ffb0", exp="masterclass",
         tip="The days around the equinox are statistically the best of the year. Plan for several nights outside.",
         body="<p>Earth's magnetic field lines up with the solar wind twice a year, making geomagnetic storms more likely around the equinoxes. It is the great aurora season opener.</p>",
         schedule=[("21:00", "Equinox supper", True), ("23:00", "Sky watch", True), ("01:00", "Long exposure clinic", False)], art=dict(palette="emerald", motif="cabin", seed=51)),
    dict(title="Southern Lights Window: Tasmania", type="storm_watch", start="2027-04-01", end="2027-04-05", vis=7, kp=6, stream=False, color="#b388ff", exp="tasmania",
         tip="Face south over the ocean and look low on the horizon. The aurora australis often shows as a pink glow before it climbs.",
         body="<p>Post-equinox conditions often favour the southern oval. Our Tasmania team will be on the cliffs with cameras ready.</p>",
         schedule=[("20:00", "Cliff camp dinner", True), ("23:00", "Southern sky watch", True)], art=dict(palette="violet", motif="ice", seed=52)),
]

# ---------------------------------------------------------------- journal posts
POSTS = [
    dict(title="What a Kp 8 Night Actually Feels Like", deck="Notes from the loudest sky I have ever stood under.", author="amara", on="2026-09-12", category="dispatch", mood="electric", tags=["kp_index", "history"], mins=6, featured=True, palette="#37ffb0", exp="fjord",
         pull="The sky did not flicker. It boiled, rolled, and then — for about ninety seconds — it was everywhere.",
         art=dict(palette="emerald", motif="pines", seed=61, moon=False),
         body="<p>The alert came at 21:14. By 21:40 the forecast desk was empty because everyone was outside.</p><p>A Kp 8 is the sort of geomagnetic storm that happens a few times in a solar cycle. The aurora stops being a band of light and becomes a dome. There is a moment, called the corona, when the rays appear to radiate from a single point directly overhead, and you understand at once why so many cultures saw it as a door.</p><h3>What the instruments saw</h3><p>Heimdall recorded a magnetic disturbance of more than 600 nanotesla in ten minutes. Skald-1's frames saturated. The spectrograph, still in calibration, caught a clean red line at 630 nm: oxygen, very high, very rare.</p><blockquote>In twenty-two years, I have never been so glad to be wrong about a forecast.</blockquote><p>Then the storm passed, the temperature dropped, and we went inside and ate soup at 1 a.m. like nothing had happened.</p>"),
    dict(title="The Sound of the Aurora", deck="A recording of the crackle scientists argued about for a century.", author="priya", on="2026-08-28", category="science", mood="eerie", tags=["sound", "kp_index"], mins=7, featured=True, palette="#b388ff", exp=None,
         pull="The sound is real. It is also about seventy metres above your head, which is the part that keeps me awake.",
         art=dict(palette="violet", motif="dome", seed=62),
         body="<p>For decades, people who spent long nights under the aurora reported a faint crackling. Scientists dismissed it. Sound cannot travel from the upper atmosphere to the ground, they said, and they were correct.</p><p>But the sound turned out to come from somewhere much closer. During strong auroras a cold layer of air forms near the ground, and electrical discharges in that layer make the crackle.</p><h3>How we recorded it</h3><p>Three microphones, a solar-powered recorder, and two weeks of patience. The clip on the station's instruments page is unfiltered.</p><ul><li>Microphones 50 metres apart</li><li>Synchronised to the magnetometer</li><li>Nothing edited, nothing added</li></ul>"),
    dict(title="Why Is the Aurora Green?", deck="Oxygen, altitude, and the physics of a very specific photon.", author="amara", on="2026-08-05", category="science", mood="calm", tags=["kp_index"], mins=5, featured=False, palette="#22d3ee", exp=None,
         pull="Every auroral colour is an atom returning to rest. The green is just the easiest to reach.",
         art=dict(palette="glacier", motif="cabin", seed=63),
         body="<p>The green glow is oxygen at about 100 kilometres altitude, releasing light at 557.7 nanometres. Oxygen higher up, where collisions are rare, takes longer to relax and emits red. Nitrogen gives the blue-violet edges.</p><p>Human eyes are most sensitive to green, which is partly why it feels so bright. A camera sees the other colours more easily than you do.</p>"),
    dict(title="Packing for Minus Thirty", deck="Saoirse's ruthless list, tested on 140 trips.", author="saoirse", on="2026-07-19", category="gear", mood="calm", tags=["packing", "cold_weather"], mins=8, featured=False, palette="#ff80ab", exp="brooks",
         pull="Cold is not the enemy. Sweat is. Everything I own exists to keep one of them out.",
         art=dict(palette="crimson", motif="tent", seed=64),
         body="<p>Layers trap heat. Cotton traps water. Bring neither cotton nor optimism.</p><h3>The system</h3><ul><li><strong>Base:</strong> merino, not cotton</li><li><strong>Mid:</strong> fleece or down</li><li><strong>Shell:</strong> windproof with a hood big enough for a beanie</li><li><strong>Hands:</strong> thin liner gloves inside big mittens</li><li><strong>Feet:</strong> one pair of socks, not two, in boots a size too large</li></ul><p>The single most forgotten item is a spare battery kept in an inside pocket. Cold drains a phone in minutes.</p>"),
    dict(title="Forty Paws, One Rhythm", deck="Learning to mush from the man who named every dog.", author="kaito", on="2026-06-30", category="dispatch", mood="triumphant", tags=["wildlife", "cold_weather"], mins=5, featured=True, palette="#ffd166", exp="midnight",
         pull="You do not drive a dog team. You agree with it.",
         art=dict(palette="solar", motif="sled", seed=65, moon=True),
         body="<p>On your first run the dogs ignore you. On your second they tolerate you. On your third, if you stop gripping the handlebar with both fists, they start to listen.</p><p>A husky team is not a vehicle; it is a conversation. Every dog has a job, a mood and an opinion about the trail. The leader reads your voice, the wheel dogs handle the corners, and everyone in between is just happy to be there.</p>"),
    dict(title="Fox Fires and Other Names for the Lights", deck="What different peoples called the aurora, and what that says about us.", author="mikkel", on="2026-06-11", category="folklore", mood="eerie", tags=["myth", "history"], mins=9, featured=False, palette="#82b1ff", exp=None,
         pull="The Finns say a fox runs across the snow so fast its tail throws sparks into the sky. I prefer that to most theories.",
         art=dict(palette="royal", motif="pines", seed=66),
         body="<p>In Finnish, the aurora is <em>revontulet</em>: fox fires. In parts of Scandinavia it was the reflection of herring shoals. Elsewhere, the lights were spirits, dancers, torches, the swords of warriors.</p><p>What all these explanations share is a human desire to give the sky a story. We do the same today with solar wind and magnetic fields. The language has changed; the wonder has not.</p><blockquote>A story is a map for a place you cannot walk to.</blockquote>"),
    dict(title="Long Exposure Cheat Sheet", deck="Seven settings, one tripod, no excuses.", author="tomas", on="2026-05-22", category="photography", mood="calm", tags=["long_exposure", "packing"], mins=6, featured=False, palette="#b388ff", exp="masterclass",
         pull="The best aurora camera is the one that is already on the tripod when the sky starts.",
         art=dict(palette="violet", motif="pines", seed=67, reflect=True),
         body="<p>Start here and adjust:</p><ul><li><strong>Lens:</strong> widest and fastest you own</li><li><strong>Aperture:</strong> wide open</li><li><strong>ISO:</strong> 1600</li><li><strong>Shutter:</strong> 8 seconds for moving aurora, 15 for calm</li><li><strong>Focus:</strong> manual, on a bright star, then tape the ring</li><li><strong>White balance:</strong> 3500-4000 K</li><li><strong>Format:</strong> RAW</li></ul><p>Check your histogram, not your screen. Your screen lies in the dark.</p>"),
    dict(title="Inside the Magnetometer Hut", deck="The quietest building in the north, and the loudest instrument.", author="priya", on="2026-04-30", category="science", mood="calm", tags=["kp_index", "sound"], mins=5, featured=False, palette="#69f0ae", exp=None,
         pull="We built it from wood and brass because steel would have lied to us.",
         art=dict(palette="emerald", motif="cabin", seed=68),
         body="<p>Forty metres from the road, buried under a turf roof, sits a hut with no nails. The floor is pegged, the door is hinged on brass, and the sensors sit on a concrete pillar that does not touch the floor.</p><p>Everything is designed not to disturb the earth's field, which is the thing it is there to measure.</p>"),
    dict(title="The Night the Telegraphs Caught Fire", deck="The 1859 Carrington Event, and what it would mean today.", author="amara", on="2026-03-14", category="science", mood="electric", tags=["history", "kp_index"], mins=10, featured=False, palette="#ff5c8a", exp=None,
         pull="In 1859, the aurora was seen in the Caribbean and telegraph operators worked without batteries.",
         art=dict(palette="crimson", motif="ice", seed=69),
         body="<p>In September 1859 a giant solar flare was followed by the largest geomagnetic storm on record. Auroras lit the sky as far south as Cuba. Telegraph systems failed, sparked, and in some cases set paper on fire.</p><p>A storm of the same size today would threaten power grids and satellites. That is why forecasting matters, and why a small observatory in the north spends its nights staring upward.</p>"),
    dict(title="Reading the Forecast Like a Pilot", deck="Kp, Bz and solar wind speed: the three numbers that matter.", author="amara", on="2026-02-18", category="science", mood="calm", tags=["kp_index"], mins=7, featured=False, palette="#22d3ee", exp=None,
         pull="Bz pointing south is the magic phrase. If you learn only one thing from this page, learn that.",
         art=dict(palette="glacier", motif="dome", seed=70),
         body="<p>Kp is a rough score of the last three hours. Bz tells you what is happening now: when the interplanetary magnetic field points south, it opens a door in Earth's shield. Solar wind speed tells you how hard the door is being pushed.</p><ul><li><strong>Kp 3-4:</strong> good aurora if you are near the oval</li><li><strong>Kp 5-6:</strong> strong, visible further south</li><li><strong>Kp 7+:</strong> drop everything</li></ul>"),
]

# ---------------------------------------------------------------- gallery
# (key, title, size(w,h), palette, motif, region, date, exposure, iso, lens, conditions, kp, hero, photographer, caption, extra art kwargs)
PHOTOS = [
    ("gal_emerald_curtain", "Emerald Curtain over Hallvarden", (1800, 1200), "emerald", "pines", "arctic_norway", "2026-01-18", 8, 1600, "14mm f/1.8", "crystal_clear", 5, True, "ingrid", "A single curtain, full width, barely moving. We held the boat still for twenty minutes.", dict(moon=False)),
    ("gal_violet_crown", "Violet Crown", (1200, 1800), "violet", "dome", "swedish_lapland", "2026-03-21", 6, 3200, "16mm f/2.8", "crystal_clear", 7, True, "tomas", "The corona forming overhead, shot from inside the station's courtyard.", dict()),
    ("gal_cabin_corona", "Cabin Under the Corona", (1800, 1200), "violet", "cabin", "yukon", "2025-10-09", 10, 1600, "20mm f/1.8", "thin_cloud", 5, False, "saoirse", "A cabin window glowing amber against a violet sky.", dict(reflect=True)),
    ("gal_sled_line", "Sled Line at Midnight", (1800, 1200), "solar", "sled", "finnish_lapland", "2026-02-08", 8, 2500, "24mm f/1.4", "moonlit", 4, False, "kaito", "The team at rest, tracks curving into the dark.", dict(moon=True)),
    ("gal_ice_teeth", "Ice Teeth, Green Sky", (1800, 1200), "glacier", "ice", "greenland", "2026-03-15", 12, 1600, "14mm f/2.8", "crystal_clear", 6, True, "ingrid", "Sea ice pushed into blades, lit by the aurora.", dict()),
    ("gal_tent_village", "Tent Village Glow", (1800, 1200), "emerald", "tent", "alaska", "2025-09-29", 15, 2000, "16mm f/2", "crystal_clear", 6, False, "saoirse", "Our camp in the Brooks Range, every tent lit from inside.", dict()),
    ("gal_lake_two_skies", "Lake of Two Skies", (1800, 1200), "royal", "pines", "yukon", "2026-09-18", 13, 1600, "14mm f/1.8", "crystal_clear", 5, True, "tomas", "A perfect reflection: the aurora above, and its twin below.", dict(reflect=True)),
    ("gal_crimson_substorm", "Crimson Substorm", (1800, 1200), "crimson", "ice", "tasmania", "2026-04-02", 15, 3200, "14mm f/2.8", "crystal_clear", 6, True, "tomas", "A southern-lights display from the Tasmanian coast, pink over the ocean.", dict()),
    ("gal_dome_wakes", "The Dome Wakes", (1200, 1800), "glacier", "dome", "svalbard", "2026-01-11", 8, 1600, "16mm f/2.8", "thin_cloud", 5, False, "priya", "Norn's dome opening as the aurora begins.", dict()),
    ("gal_pine_cathedral", "Pine Cathedral", (1200, 1800), "emerald", "pines", "finnish_lapland", "2025-12-14", 10, 1600, "14mm f/1.8", "crystal_clear", 4, False, "kaito", "Frosted spruce making a nave of the forest, green light for a ceiling.", dict(moon=True)),
    ("gal_golden_hour", "Solar Gold at the Fjord", (1800, 1200), "solar", "pines", "arctic_norway", "2025-11-22", 5, 800, "24mm f/1.8", "moonlit", 3, False, "ingrid", "A warmer palette: solar particles and a low moon.", dict(moon=True)),
    ("gal_iceland_lagoon", "Lagoon Steam", (1800, 1200), "royal", "cabin", "iceland", "2026-10-05", 10, 2000, "16mm f/2", "thin_cloud", 5, False, "hallbera", "Steam off a geothermal lagoon with the lights coming in.", dict(reflect=True)),
    ("gal_equinox_night", "Equinox Night", (1800, 1200), "emerald", "dome", "swedish_lapland", "2026-03-20", 8, 1600, "16mm f/2.8", "crystal_clear", 7, True, "amara", "Five hours of continuous activity at the spring equinox.", dict()),
    ("gal_storm_dome", "Storm Dome", (1200, 1800), "crimson", "pines", "arctic_norway", "2026-09-12", 4, 3200, "14mm f/1.8", "storm", 8, True, "amara", "The Kp 8 night. Sky bright enough to read by.", dict()),
    ("gal_quiet_blue", "A Quiet Blue", (1800, 1200), "glacier", "tent", "greenland", "2026-03-16", 20, 1600, "24mm f/1.4", "moonlit", 2, False, "ingrid", "A very quiet night on the ice: no storm, just a soft blue band.", dict(moon=True)),
    ("gal_violet_ridge", "Violet over the Ridge", (1800, 1200), "violet", "ice", "alaska", "2025-10-02", 12, 1600, "20mm f/1.8", "crystal_clear", 5, False, "saoirse", "A long, violet ribbon curling over the Brooks Range.", dict()),
]
