"""Expeditions, each with a day-by-day itinerary."""

# itinerary row: (day, title, details, lodging, distance_km, aurora_night)
EXPEDITIONS = {
    "fjord": dict(
        title="Fjord of Glass: The Arctic Norway Aurora Sail", tagline="Four nights on a schooner, one sky that never sits still.",
        summary="Sail a quiet arctic fjord aboard a restored 1930s schooner, anchoring each night beneath the auroral oval with Ingrid Solvang at the helm.",
        region="arctic_norway", difficulty="moderate", seasons=["nov_dec", "jan_feb"], departure="2027-01-14", nights=7, price=4850, group=12, odds=88, featured=True,
        guide="ingrid", accent="#37ffb0", art=dict(palette="emerald", motif="pines", seed=21, reflect=True, moon=False),
        story="""<p>The <em>Havbris</em> is a 28-metre schooner with creaking timbers, a wood-fired galley and a mast that scrapes the stars. For seven nights she drifts through a fjord so still that the aurora doubles itself on the water.</p><h3>Why this route</h3><p>The oval of peak auroral activity passes almost directly over this stretch of coast. Mountains on both sides shelter the water from wind, and the town lights are a two-hour sail behind you.</p><ul><li>Anchor each night in a different bay chosen that afternoon from the forecast</li><li>Shore landings by skiff for sunrise hikes and sauna by the fjord</li><li>Hot cocoa at 2 a.m. whether you asked for it or not</li></ul><blockquote>We chase the clear sky, not the schedule. If the forecast says go, we sail in the dark.</blockquote><p>You will sleep in a four-berth cabin, eat fish caught that morning, and learn to read the sky from the people who have been doing it for thirty years.</p>""",
        itinerary=[
            ("Day 1", "Board the Havbris", "Welcome dinner in the old harbour, cast off at dusk, first anchorage under the stars.", "ship", 12, False),
            ("Day 2", "Into the narrows", "Sail between 900-metre walls. Afternoon kayaking; evening forecast briefing with Ingrid.", "ship", 46, True),
            ("Day 3", "Shore day and sauna", "Landing at an abandoned fishing station, wood-fired sauna, then a long-exposure workshop on the foredeck.", "ship", 18, True),
            ("Day 4", "The wide bay", "Our best aurora odds. We anchor early, eat early, and stay out until the sky lets us go.", "ship", 31, True),
            ("Day 5", "Glacier tongue", "Sail to the head of the fjord and walk to a glacier's edge at noon light.", "ship", 52, False),
            ("Day 6", "Reversing course", "A slow, windless sail home. Mikkel tells the story of the fox fires over dinner.", "ship", 60, True),
            ("Day 7", "Farewell harbour", "Breakfast, a final sail into town, and a printed photo from the trip.", "hotel", 25, False),
        ],
        moments=[("Anchored under the corona", "gal_emerald_curtain"), ("Skiff landing at dusk", "gal_lake_two_skies"), ("Green on black water", "gal_pine_cathedral")],
    ),
    "midnight": dict(
        title="Lapland Sled-Dog Midnight Run", tagline="Drive your own husky team through a forest lit from above.",
        summary="Five nights in Finnish Lapland learning to mush a team of huskies under the aurora, with sauna, reindeer stew and real silence.",
        region="finnish_lapland", difficulty="moderate", seasons=["jan_feb", "mar_apr"], departure="2027-02-06", nights=5, price=3900, group=8, odds=82, featured=True,
        guide="kaito", accent="#ffd166", art=dict(palette="solar", motif="sled", seed=22, moon=True),
        story="""<p>There is a moment, about twenty minutes into your first solo run, when the dogs fall quiet, the runners hiss, and the green light arrives above the spruce. Kaito promises you will not be able to describe it afterwards.</p><h3>What you will do</h3><ul><li>Learn to drive a four-dog sled in a single afternoon</li><li>Run a moonlit forest trail to a fire-lit cabin</li><li>Visit the kennel at feeding time and meet every dog by name</li></ul><p>Nights are spent in a heated log lodge with a wood sauna and a window seat designed for lying awake.</p>""",
        itinerary=[
            ("Day 1", "Arrival and the kennel", "Meet Kaito's thirty-one huskies and get your snow gear fitted.", "lodge", 0, False),
            ("Day 2", "Sled school", "Morning lessons, afternoon forest loop, evening sauna.", "lodge", 22, True),
            ("Day 3", "The long trail", "A full-day run to a remote cabin where we sleep under the open sky.", "cabin", 48, True),
            ("Day 4", "Frozen lake crossing", "Cross a two-metre-thick lake, ice-fish for lunch, and run home by moonlight.", "lodge", 35, True),
            ("Day 5", "Last run", "A slow morning, your own fastest loop, and a farewell feast.", "lodge", 15, False),
        ],
        moments=[("Sled line at midnight", "gal_sled_line"), ("Cabin window glow", "gal_cabin_corona")],
    ),
    "cabin": dict(
        title="Yukon Dark-Sky Cabin Retreat", tagline="A private log cabin, a hot tub, and the whole sky to yourself.",
        summary="The gentlest way to see the aurora: six nights in a lakeside cabin in the Yukon with a hot tub, guided evenings and optional snowshoe days.",
        region="yukon", difficulty="gentle", seasons=["sep_oct", "mar_apr"], departure="2026-10-17", nights=6, price=3650, group=10, odds=79, featured=False,
        guide="saoirse", accent="#ff80ab", art=dict(palette="crimson", motif="cabin", seed=23, reflect=True),
        story="""<p>No early starts, no long transfers, no sleeping in a tent. You arrive, unpack, soak in a cedar hot tub, and wait for the sky to do something.</p><h3>Designed for unhurried evenings</h3><ul><li>Private log cabins scattered along a frozen lake</li><li>Aurora wake-up calls only if you ask for them</li><li>Optional snowshoe and ice-fishing days led by Saoirse</li></ul><p>It is the retreat we recommend to first-time aurora chasers, and to people who have already chased it too hard.</p>""",
        itinerary=[
            ("Day 1", "Lakeside arrival", "Airport pickup, cabin check-in and a long hot dinner.", "cabin", 60, False),
            ("Day 2", "Do nothing well", "Late brunch, optional snowshoe, evening watch from the hot tub.", "cabin", 4, True),
            ("Day 3", "Ice fishing and stew", "Fish for trout through the ice; Saoirse cooks whatever you catch.", "cabin", 8, True),
            ("Day 4", "Mountain ridge", "A gentle ridge walk with a view to the horizon, then a slow glide home.", "cabin", 10, True),
            ("Day 5", "Photography night", "Tripod lessons on the lake with Tomás joining by video.", "cabin", 0, True),
            ("Day 6", "Sleep in", "Nothing planned except goodbye.", "cabin", 60, False),
        ],
        moments=[("Corona over the cabin", "gal_cabin_corona"), ("The lake at midnight", "gal_lake_two_skies")],
    ),
    "iceland": dict(
        title="Iceland: Ring of Fire and Light", tagline="Lava fields, geothermal lagoons and a sky that matches both.",
        summary="Eight nights around Iceland's ring road with volcanologist Hallbera Jónsdóttir: waterfalls by day, aurora watches in steaming lagoons by night.",
        region="iceland", difficulty="moderate", seasons=["sep_oct", "nov_dec", "mar_apr"], departure="2026-11-07", nights=8, price=5200, group=12, odds=76, featured=True,
        guide="hallbera", accent="#ff8a65", art=dict(palette="royal", motif="ice", seed=24, moon=True),
        story="""<p>Iceland is the rare destination where the ground and the sky are both active. Hallbera builds each day around a single idea: geology in the morning, light in the evening.</p><h3>Highlights</h3><ul><li>A private late-night soak in a geothermal lagoon beneath the aurora</li><li>Ice caves, black-sand beaches and three separate waterfalls</li><li>Dinner in a greenhouse heated by a volcano</li></ul><blockquote>The aurora is never the only reason to be there. It is just the best one.</blockquote>""",
        itinerary=[
            ("Day 1", "Reykjavik and the lagoon", "Arrival, dinner, and a first soak.", "hotel", 50, False),
            ("Day 2", "Golden circle", "Geysers, rift valleys and a waterfall at sunset.", "lodge", 240, True),
            ("Day 3", "South coast", "Black-sand beaches and a glacier hike.", "lodge", 190, True),
            ("Day 4", "Glacier lagoon", "Drift among icebergs, then a night watch on the shore.", "lodge", 260, True),
            ("Day 5", "East fjords", "Quiet villages and a lava-field picnic.", "lodge", 210, False),
            ("Day 6", "Volcano country", "Steam fields, mud pools, and a greenhouse dinner.", "lodge", 180, True),
            ("Day 7", "Northern waterfalls", "Thunderous falls, then a last aurora watch.", "hotel", 160, True),
            ("Day 8", "Return south", "Scenic drive, farewell lunch and airport drop.", "hotel", 300, False),
        ],
        moments=[("Ice teeth, green sky", "gal_ice_teeth"), ("Steam and stars", "gal_violet_crown")],
    ),
    "greenland": dict(
        title="Greenland Ice-Cap Vigil", tagline="Ten days on the ice with the quietest sky on Earth.",
        summary="A serious expedition: ten nights camped on and beside the Greenland ice sheet, far from any light, with a team of eight and two guides.",
        region="greenland", difficulty="extreme", seasons=["sep_oct", "mar_apr"], departure="2027-03-12", nights=10, price=8900, group=8, odds=91, featured=False,
        guide="amara", accent="#82b1ff", art=dict(palette="glacier", motif="ice", seed=25),
        story="""<p>The ice cap is the darkest place we operate. There are no cabins, no hot tubs and no phone coverage, only the horizon, the sled you pull and the sky that finishes the job.</p><h3>Not for everyone</h3><p>This is a physical expedition. You should be comfortable hauling a pulk for six hours a day at minus twenty-five. We will train you, but we cannot carry you.</p><ul><li>Heated four-season tents with a wood stove for the mess tent</li><li>A full-time medic and satellite communications</li><li>Nightly aurora talks from Amara, who is also our space-weather forecaster</li></ul>""",
        itinerary=[
            ("Day 1", "Kangerlussuaq", "Arrival, gear check and cold-weather briefing.", "hotel", 0, False),
            ("Day 2", "To the ice edge", "Overland transfer and first camp on the moraine.", "tent", 40, False),
            ("Day 3", "Onto the sheet", "First pulk day, six hours on skis.", "tent", 14, True),
            ("Day 4", "Whiteout training", "Navigation, rope work and a rest afternoon.", "tent", 8, True),
            ("Day 5", "Deep camp", "Our furthest camp. The darkest sky of the trip.", "tent", 16, True),
            ("Day 6", "Stay a day", "Rest, repair and sky-watching.", "tent", 0, True),
            ("Day 7", "Crevasse country", "Roped travel across a glacial tongue.", "tent", 12, True),
            ("Day 8", "Heading down", "Descend toward the coast.", "tent", 15, False),
            ("Day 9", "Last camp", "Celebration dinner in the mess tent.", "tent", 10, True),
            ("Day 10", "Return", "Transfer back to Kangerlussuaq and hot showers.", "hotel", 40, False),
        ],
        moments=[("Tents under the corona", "gal_tent_village"), ("Ice and green light", "gal_ice_teeth")],
    ),
    "tasmania": dict(
        title="Tasmania Aurora Australis Chase", tagline="The southern lights are real. Come see them from a cliff.",
        summary="Six nights on Tasmania's southern coast, where the aurora australis paints the horizon, led by astrophotographer Tomás Arriaga.",
        region="tasmania", difficulty="gentle", seasons=["mar_apr", "sep_oct"], departure="2027-04-03", nights=6, price=4100, group=10, odds=58, featured=True,
        guide="tomas", accent="#b388ff", art=dict(palette="violet", motif="cabin", seed=26, moon=True),
        story="""<p>The southern aurora is less famous than its northern twin, and in some ways more rewarding. It hangs low and pink over an empty ocean, and there is no one within two thousand kilometres looking at the same sky.</p><h3>Tomás's rules</h3><ul><li>Dark-sky cliff camp, 40 minutes from the nearest streetlight</li><li>Astro-photography coaching every night, even cloudy ones</li><li>Wombats, wallabies and Tasmanian devils at the edge of the campfire light</li></ul><p>Odds are lower than the Arctic. We say so openly, and we plan for the gaps with telescopes and stories.</p>""",
        itinerary=[
            ("Day 1", "Hobart arrival", "Dinner and a night-sky briefing.", "hotel", 25, False),
            ("Day 2", "South to the cape", "Drive the coast and set up camp on the cliff.", "tent", 130, True),
            ("Day 3", "Coastal walk", "A five-hour walk along sea cliffs.", "tent", 12, True),
            ("Day 4", "Astro-photography day", "A full workshop on stacking, focus and star trails.", "tent", 0, True),
            ("Day 5", "Devil sanctuary", "Meet the wildlife, then return to camp.", "tent", 35, True),
            ("Day 6", "Return", "Breakfast on the cliff and back to Hobart.", "hotel", 130, False),
        ],
        moments=[("Crimson on the horizon", "gal_crimson_substorm"), ("Tent lights", "gal_tent_village")],
    ),
    "svalbard": dict(
        title="Svalbard Polar Night Expedition", tagline="Nine days of darkness, and everything that glows inside it.",
        summary="The polar night at 78° north: no sunrise for weeks, guaranteed dark skies, and aurora watching from sled, snowmobile and ice cave.",
        region="svalbard", difficulty="demanding", seasons=["nov_dec", "jan_feb"], departure="2026-12-05", nights=9, price=9400, group=10, odds=94, featured=True,
        guide="ingrid", accent="#22d3ee", art=dict(palette="royal", motif="ice", seed=27),
        story="""<p>At 78° north, the sun does not rise for months. The sky is a permanent blue twilight at midday and an infinite black after, which makes every aurora doubly bright.</p><h3>Expedition highlights</h3><ul><li>Snowmobile safaris across the frozen valley</li><li>A night inside a natural ice cave</li><li>Dinner in a former mining town's last standing restaurant</li></ul><p>Expect long days, serious cold and the best aurora odds of any trip we run.</p>""",
        itinerary=[
            ("Day 1", "Longyearbyen", "Arrival and polar bear safety briefing.", "hotel", 0, False),
            ("Day 2", "Dog-sled valley", "Sled through a moonlit valley.", "lodge", 30, True),
            ("Day 3", "Ice cave", "Descend into a blue ice cave and sleep beside it.", "tent", 25, True),
            ("Day 4", "Coal-town ruins", "A haunting walk through an abandoned Soviet mining town.", "lodge", 40, True),
            ("Day 5", "Snowmobile day", "A long ride to the eastern coast.", "lodge", 110, True),
            ("Day 6", "Polar twilight", "A midday blue hour and a photography workshop.", "lodge", 20, True),
            ("Day 7", "Research station", "Visit an Arctic research station and talk to real scientists.", "station", 30, True),
            ("Day 8", "Aurora dinner", "Seven courses beneath an open sky.", "hotel", 5, True),
            ("Day 9", "Departure", "Transfer to the airport.", "hotel", 10, False),
        ],
        moments=[("Ice cave light", "gal_ice_teeth"), ("Polar night ribbon", "gal_dome_wakes")],
    ),
    "brooks": dict(
        title="Alaska Brooks Range Wilderness", tagline="Fly in, hike out, and sleep under a sky nobody has named yet.",
        summary="Eight days in the Brooks Range, reached only by bush plane, with backcountry camps, big mountains and some of North America's clearest auroras.",
        region="alaska", difficulty="demanding", seasons=["sep_oct", "mar_apr"], departure="2026-10-24", nights=8, price=6300, group=8, odds=86, featured=False,
        guide="saoirse", accent="#69f0ae", art=dict(palette="emerald", motif="tent", seed=28),
        story="""<p>There are no roads into this valley. A bush pilot drops you at a gravel bar beside a river, and eight days later the same pilot comes back to collect the people who did not want to leave.</p><h3>Backcountry style</h3><ul><li>Heated tent camps with a mess tent and wood stoves</li><li>Day hikes ranging from easy to very serious</li><li>A full-time wilderness medic in the team</li></ul>""",
        itinerary=[
            ("Day 1", "Fairbanks", "Gear check and pre-trip briefing.", "hotel", 0, False),
            ("Day 2", "Bush flight", "Fly north over the Arctic Circle and land on a river bar.", "tent", 380, False),
            ("Day 3", "Valley walk", "Explore the valley with your guide.", "tent", 12, True),
            ("Day 4", "Ridge day", "Climb to a ridge for a 360-degree sky.", "tent", 15, True),
            ("Day 5", "Rest and photography", "A slow day with a photo workshop.", "tent", 4, True),
            ("Day 6", "Upper lake", "Hike to a high lake and camp.", "tent", 18, True),
            ("Day 7", "Return valley", "Descend and feast.", "tent", 16, True),
            ("Day 8", "Fly out", "Bush plane back to Fairbanks.", "hotel", 380, False),
        ],
        moments=[("Camp under green fire", "gal_tent_village"), ("Kp 6 over the ridge", "gal_violet_crown")],
    ),
    "skystation": dict(
        title="Sky Station Weekend", tagline="Two nights at our own observatory, forecast desk included.",
        summary="Our shortest trip: a long weekend at the Aurora Observatory itself, with behind-the-scenes access to every instrument and the forecast desk.",
        region="swedish_lapland", difficulty="gentle", seasons=["sep_oct", "nov_dec", "jan_feb", "mar_apr"], departure="2026-11-20", nights=3, price=2850, group=14, odds=74, featured=False,
        guide="amara", accent="#37ffb0", art=dict(palette="glacier", motif="dome", seed=29),
        story="""<p>Want to see how the prediction works? Come to the place that makes it. Amara runs the forecast desk herself and will let you sit beside her while the solar wind changes.</p><h3>Included</h3><ul><li>Private tours of the magnetometer hut, spectrograph lab and public telescope dome</li><li>A guided sky-watching session every night</li><li>A talk from Amara on how the Sun writes the aurora</li></ul>""",
        itinerary=[
            ("Day 1", "Welcome to the station", "Tour the campus and meet the team.", "station", 0, True),
            ("Day 2", "Instruments day", "Hands-on time with every sensor.", "station", 0, True),
            ("Day 3", "Forecast desk", "Shadow Amara at the forecast desk.", "station", 0, True),
            ("Day 4", "Farewell brunch", "A last look at the sky, then home.", "station", 0, False),
        ],
        moments=[("The dome wakes", "gal_dome_wakes"), ("Violet crown", "gal_violet_crown")],
    ),
    "masterclass": dict(
        title="Photographer's Masterclass: Lofoten", tagline="Seven nights, eleven keepers, one sky worth framing.",
        summary="Seven nights on the Lofoten islands with Tomás Arriaga: a proper workshop for photographers who want more than a lucky shot.",
        region="arctic_norway", difficulty="moderate", seasons=["sep_oct", "mar_apr"], departure="2027-03-26", nights=7, price=5600, group=8, odds=84, featured=True,
        guide="tomas", accent="#b388ff", art=dict(palette="violet", motif="pines", seed=30, reflect=True),
        story="""<p>Lofoten has the best foreground in the north: jagged peaks, red fishing huts, white beaches and black water. Tomás shows you how to build a frame around all of it.</p><h3>Curriculum</h3><ul><li>Night 1: Reading the forecast and finding your location</li><li>Night 3: Long exposure, star trails and noise control</li><li>Night 5: Panoramas and blending</li><li>Night 7: Print critique over dinner</li></ul><p>Bring a camera that can shoot manual and a tripod that does not wobble.</p>""",
        itinerary=[
            ("Day 1", "Fishing-village arrival", "Settle into a seaside cabin.", "cabin", 50, False),
            ("Day 2", "Locations scouting", "Scout the best compositions by daylight.", "cabin", 60, True),
            ("Day 3", "Long-exposure night", "Practical night session.", "cabin", 25, True),
            ("Day 4", "Beach and peaks", "Shoot from a white beach beneath jagged peaks.", "cabin", 30, True),
            ("Day 5", "Panorama night", "Shoot and stitch a full panorama.", "cabin", 20, True),
            ("Day 6", "Edit day", "Process your best frames together.", "cabin", 0, True),
            ("Day 7", "Print critique", "Dinner and feedback from Tomás.", "cabin", 0, True),
            ("Day 8", "Farewell", "Depart with a full memory card.", "hotel", 50, False),
        ],
        moments=[("Red huts, green sky", "gal_cabin_corona"), ("Star trail arcs", "gal_pine_cathedral"), ("Reflected ribbon", "gal_lake_two_skies")],
    ),
}
