"""Guides, instruments and voices (the people and kit behind the station)."""

GUIDES = {
    "ingrid": dict(
        title="Ingrid Solvang", role="Head of Expeditions", accent="#37ffb0", years=19, region="arctic_norway",
        skills=["aurora_photography", "sailing", "space_weather"], langs=["english", "norwegian", "german"], lead=True,
        quote="The sky does not owe you a show. Show up every night anyway, and eventually it pays you back in full.",
        bio="<p>Ingrid grew up on a fishing island where the lights were simply part of the weather. She skippered her first fjord crossing at sixteen and has led more than three hundred aurora expeditions since.</p><p>She designs every Aurora Observatory route herself, and will happily tell you which ones she would not sell to her own mother.</p>",
        links=[("instagram", "@ingrid.under.the.lights"), ("mastodon", "@ingrid@sky.social")],
        portrait=dict(palette="emerald", skin="#f1c7a8", hair="#d8b27a", style="long", garment="#1f4a5e", beanie=None),
    ),
    "tomas": dict(
        title="Tomás Arriaga", role="Astrophotography Lead", accent="#b388ff", years=14, region="tasmania",
        skills=["aurora_photography", "astronomy", "geology"], langs=["english", "spanish", "french"], lead=True,
        quote="A photograph of the aurora is a promise you keep to the people who were not there.",
        bio="<p>Tomás left a career in satellite imaging to chase the southern lights from Tasmania and the northern ones from everywhere else. His long-exposure workshops are the reason half our travellers now own a tripod they swear they will never pack again.</p>",
        links=[("website", "tomasarriaga.example"), ("youtube", "@TomasTimelapse")],
        portrait=dict(palette="violet", skin="#c68a62", hair="#1b1410", style="short", garment="#3b2a5e", beanie="#37ffb0"),
    ),
    "amara": dict(
        title="Dr. Amara Okonkwo-Reyes", role="Station Director", accent="#22d3ee", years=22, region="swedish_lapland",
        skills=["space_weather", "astronomy", "instrument_engineering"], langs=["english", "yoruba", "swedish", "spanish"], lead=True,
        quote="Space weather is just weather that happens to be eight light-minutes away. Learn to read it and the whole sky opens up.",
        bio="<p>Amara is a heliophysicist who traded a university chair for a cabin with a magnetometer hut. She leads the station's forecasting desk and personally signs off every Kp alert that goes out to guests.</p><p>She has published more than forty papers and answers questions at dinner with the patience of someone who has heard them all and loved each one.</p>",
        links=[("bluesky", "@amara.kp"), ("website", "spaceweather.example/amara")],
        portrait=dict(palette="glacier", skin="#8a5a3c", hair="#0f0b0a", style="curly", garment="#0e5d63", beanie=None),
    ),
    "kaito": dict(
        title="Kaito Lindqvist", role="Head Musher", accent="#ffd166", years=16, region="finnish_lapland",
        skills=["dog_sledding", "snowshoeing", "wilderness_medicine"], langs=["finnish", "english", "swedish"], lead=False,
        quote="Forty paws, one rhythm. The aurora is the bonus; the silence is the point.",
        bio="<p>Kaito keeps a team of thirty-one huskies and can name every one of their grandparents. He teaches newcomers to drive a sled in a single afternoon, mostly by staying calm while they steer into a snowbank.</p>",
        links=[("instagram", "@kaito.and.the.pack")],
        portrait=dict(palette="solar", skin="#e6b896", hair="#2a2018", style="short", garment="#7a3b20", beanie="#e9b949"),
    ),
    "saoirse": dict(
        title="Saoirse Bellweather", role="Wilderness Medic & Guide", accent="#ff80ab", years=11, region="yukon",
        skills=["wilderness_medicine", "snowshoeing", "geology"], langs=["english", "french"], lead=False,
        quote="Warm feet, full stomach, clear head. Everything else is scenery.",
        bio="<p>Saoirse spent a decade as a search-and-rescue paramedic in the Yukon before she started guiding. Her packing checklist has saved more trips than any forecast.</p>",
        links=[("mastodon", "@saoirse@trail.town")],
        portrait=dict(palette="crimson", skin="#f5d3b9", hair="#b5522b", style="long", garment="#27466b", beanie=None),
    ),
    "mikkel": dict(
        title="Mikkel Hauge", role="Storyteller & Cultural Interpreter", accent="#82b1ff", years=27, region="arctic_norway",
        skills=["folklore", "sailing", "geology"], langs=["norwegian", "english", "german"], lead=False,
        quote="Every people who lived under the lights made up a story about them. Collect them all, and believe none of them too hard.",
        bio="<p>Mikkel is a former schoolteacher and lifelong collector of northern tales. On cold evenings he sits by the stove and tells them: fox fires, whale songs, the dead playing football with a walrus skull.</p>",
        links=[("website", "hauge-tales.example")],
        portrait=dict(palette="royal", skin="#dcae8c", hair="#9a9aa2", style="short", garment="#4a2a3a", beanie=None),
    ),
    "priya": dict(
        title="Priya Raman", role="Instrument Engineer", accent="#69f0ae", years=9, region="svalbard",
        skills=["instrument_engineering", "space_weather", "astronomy"], langs=["english", "tamil", "norwegian"], lead=False,
        quote="If a sensor can be built, it can be built to survive minus forty. That is the whole job.",
        bio="<p>Priya keeps every instrument at the station honest. She rebuilt the magnetometer array from a box of spare coils and a borrowed soldering iron, and the data has not drifted since.</p>",
        links=[("bluesky", "@priya.builds")],
        portrait=dict(palette="emerald", skin="#b9794f", hair="#120c0a", style="long", garment="#22395f", beanie=None),
    ),
    "hallbera": dict(
        title="Hallbera Jónsdóttir", role="Iceland Field Lead", accent="#ff8a65", years=13, region="iceland",
        skills=["geology", "aurora_photography", "snowshoeing"], langs=["icelandic", "english", "german"], lead=True,
        quote="Stand on ground that is still being made, under a sky that is still being lit. Iceland does both at once.",
        bio="<p>Hallbera is a volcanologist by training and a storyteller by temperament. She knows which geothermal lagoons are empty at 2 a.m. and exactly how long you can stay in one while the sky lights up.</p>",
        links=[("instagram", "@hallbera.heima"), ("youtube", "@HallberaHeima")],
        portrait=dict(palette="solar", skin="#efc9ac", hair="#e7e0d0", style="bun", garment="#0f4f4a", beanie="#ff8a65"),
    ),
}

INSTRUMENTS = {
    "skald": dict(
        title="Skald-1 All-Sky Camera", kind="all_sky_camera", status="online", installed="2019-11-03", public=True, glow="#37ffb0", cadence=10, operator="priya",
        body="<p>Skald-1 sees the whole dome of the sky through a fisheye lens, once every ten seconds, all night. Its frames feed the live aurora cam on this site and the station's alert pipeline.</p><p>Every frame is timestamped, stacked against a star map and scored for auroral brightness, which is how our guides know when to wake you.</p>",
        specs=[("Lens", "1.8 mm f/1.6 fisheye, 185° field", True), ("Sensor", "Cooled 16-bit mono CMOS", False), ("Cadence", "One frame every 10 s", True), ("Filter wheel", "557.7 nm / 630.0 nm / 427.8 nm", False), ("Archive", "14 TB and growing", False)],
        art=dict(palette="emerald", motif="dome", seed=11),
    ),
    "heimdall": dict(
        title="Heimdall Magnetometer Array", kind="magnetometer", status="online", installed="2017-08-21", public=True, glow="#22d3ee", cadence=1, operator="priya",
        body="<p>Three orthogonal fluxgate sensors buried 40 metres from the nearest metal fence, because even a parked snowmobile can ruin the signal. When the earth's field twitches, Heimdall notices a second before the sky does.</p>",
        specs=[("Sensors", "3-axis fluxgate × 3 sites", True), ("Resolution", "0.01 nT", True), ("Sample rate", "1 Hz, 50 Hz burst mode", False), ("Noise floor", "6 pT/√Hz at 1 Hz", False)],
        art=dict(palette="glacier", motif="pines", seed=12),
    ),
    "bifrost": dict(
        title="Bifrost Spectrograph", kind="spectrograph", status="calibrating", installed="2022-02-14", public=False, glow="#b388ff", cadence=30, operator="amara",
        body="<p>Bifrost splits auroral light into its component colours. The famous green is oxygen at 557.7 nanometres; the rare red, oxygen much higher up; the violet fringe, ionised nitrogen. With Bifrost we can tell you not just that the sky is glowing, but <em>what</em> is glowing.</p>",
        specs=[("Resolution", "0.08 nm", True), ("Range", "380 – 720 nm", False), ("Grating", "1800 lines/mm holographic", False), ("Exposure", "5 – 120 s", False)],
        art=dict(palette="violet", motif="dome", seed=13),
    ),
    "norn": dict(
        title="Norn 40 cm Reflector", kind="telescope", status="online", installed="2015-10-09", public=True, glow="#ffd166", cadence=0, operator="tomas",
        body="<p>The station's public telescope. On clear nights without aurora (yes, those exist), guests queue up for Saturn's rings, the Orion nebula and a moon so close you flinch. Bring a flask; the dome is unheated on purpose.</p>",
        specs=[("Aperture", "400 mm", True), ("Focal length", "1600 mm, f/4", False), ("Mount", "Direct-drive equatorial", False), ("Dome", "4.5 m, unheated", False)],
        art=dict(palette="solar", motif="dome", seed=14),
    ),
    "mimir": dict(
        title="Mimir Riometer", kind="riometer", status="maintenance", installed="2016-03-30", public=False, glow="#ff8a65", cadence=1, operator="priya",
        body="<p>A riometer measures how much cosmic radio noise the ionosphere swallows. It is the quiet instrument nobody photographs, and the one the physicists quietly love best.</p>",
        specs=[("Frequency", "38.2 MHz", True), ("Antenna", "4 × 4 crossed Yagi array", False), ("Beam width", "13°", False)],
        art=dict(palette="crimson", motif="ice", seed=15),
    ),
    "hugin": dict(
        title="Hugin Lidar", kind="lidar", status="online", installed="2024-01-18", public=True, glow="#69f0ae", cadence=60, operator="amara",
        body="<p>A pulsed green laser fired straight up, and a one-metre mirror listening for what comes back. Hugin maps the layers of the upper atmosphere where auroras actually happen, and lets guests see the beam from a kilometre away.</p>",
        specs=[("Wavelength", "532 nm Nd:YAG", True), ("Pulse rate", "50 Hz", False), ("Receiver", "1.0 m telescope", False), ("Altitude range", "30 – 110 km", True)],
        art=dict(palette="emerald", motif="cabin", seed=16),
    ),
}

VOICES = [
    dict(name="Marguerite Dubois", town="Lyon, France", rating="5", tint="#37ffb0", exp="fjord", verified=True,
         quote="I cried on deck at three in the morning and nobody thought it was strange. Ingrid simply handed me a hot chocolate and pointed at the sky.",
         story="<p>I booked the Fjord of Glass for my sixtieth birthday expecting a pleasant cruise. What I got was four nights of green fire above black water, a crew that remembered my name, and a kind of quiet I did not know existed.</p>",
         portrait=dict(palette="emerald", skin="#f3d2b9", hair="#c9c9cf", style="bun", garment="#2a3f6b", beanie=None)),
    dict(name="Daniel Okafor", town="Manchester, UK", rating="5", tint="#22d3ee", exp="midnight", verified=True,
         quote="Forty huskies, zero phone signal, and a sky that looked like someone spilled paint. Best week of my adult life.",
         story="<p>Kaito taught me to drive a dog team in an afternoon. By night three I was doing it alone under a Kp 6 sky.</p>",
         portrait=dict(palette="glacier", skin="#6b4630", hair="#0b0807", style="short", garment="#3a3a4f", beanie="#ffd166")),
    dict(name="Yuki Tanabe", town="Osaka, Japan", rating="5", tint="#b388ff", exp="masterclass", verified=True,
         quote="Tomás rebuilt my entire idea of exposure. I came for northern lights and left with a portfolio.",
         story="<p>Seven nights, eleven keepers, and one frame I am going to print two metres wide.</p>",
         portrait=dict(palette="violet", skin="#f0cdb0", hair="#14100e", style="long", garment="#5a2b5e", beanie=None)),
    dict(name="Carla & Ben Whitfield", town="Denver, USA", rating="5", tint="#ffd166", exp="cabin", verified=True,
         quote="We honeymooned in a log cabin in the Yukon with a hot tub, a woodstove and a sky that would not stop. Zero regrets.",
         story="<p>Saoirse left a thermos of cocoa on our porch every evening. The aurora did the rest.</p>",
         portrait=dict(palette="solar", skin="#f4d6bd", hair="#7a4a2a", style="long", garment="#2f5d50", beanie=None)),
    dict(name="Anders Falk", town="Gothenburg, Sweden", rating="4", tint="#82b1ff", exp="skystation", verified=True,
         quote="As an engineer I came for the magnetometers. As a human I stayed out until dawn. The forecast desk is shockingly accurate.",
         story="<p>Amara explained the solar wind to my eleven-year-old in five minutes and he has not stopped talking about it since.</p>",
         portrait=dict(palette="royal", skin="#e9c2a1", hair="#b39770", style="short", garment="#31424f", beanie=None)),
    dict(name="Priyanka Nair", town="Toronto, Canada", rating="5", tint="#ff80ab", exp="iceland", verified=True,
         quote="Soaking in a geothermal lagoon while the sky went violet. I will never be able to describe it properly, so I just tell everyone to go.",
         story="<p>Hallbera timed everything: lagoon, lava field, then the lights arrived like they had been waiting for us.</p>",
         portrait=dict(palette="crimson", skin="#b9794f", hair="#14100e", style="long", garment="#3a2a4f", beanie=None)),
    dict(name="Tobias Wren", town="Melbourne, Australia", rating="5", tint="#69f0ae", exp="tasmania", verified=False,
         quote="The southern lights were a lifelong dream. Tasmania delivered in a way I can only describe as generous.",
         story="<p>Five nights on a clifftop and we got four glowing skies. Tomás kept making tea and making miracles.</p>",
         portrait=dict(palette="emerald", skin="#eec6a4", hair="#5e4630", style="curly", garment="#22445a", beanie=None)),
    dict(name="Ingebjørg Moe", town="Bergen, Norway", rating="4", tint="#ff8a65", exp="svalbard", verified=True,
         quote="Even as a Norwegian, I was not ready for the polar night. Darkness at noon and a sky full of ribbons. Humbling.",
         story="<p>The most demanding trip I have ever taken, and the most worth it.</p>",
         portrait=dict(palette="glacier", skin="#f6d8c2", hair="#e4d7b6", style="bun", garment="#6b2b2b", beanie=None)),
]
