"""Finished ceramics for sale. Each carries art parameters (bg, speckle, secondary glaze) alongside the field values."""

CARE = {
    "default": [("Hand wash or dishwasher", "Glazes are fired to stoneware temperature and tolerate both. Hand washing keeps the sheen longest."),
                ("Avoid sudden heat", "Let the piece come to room temperature before filling it with boiling water or placing it in a hot oven."),
                ("Dry the foot", "The unglazed foot ring is porous. Stand the piece upside down for an hour so it dries fully.")],
    "plant": [("Drainage first", "There is a hole in the base. Put the saucer underneath and a layer of grit in the bottom of the pot."),
              ("Wipe, don't scrub", "A damp cloth removes limescale. Abrasives dull the glaze."),
              ("Frost", "Fired stoneware tolerates a mild frost. Bring it in if the compost is soaked and the forecast is below minus five.")],
    "lantern": [("Use a tealight or LED", "The chimney is built for a tealight. Never use a large candle: the clay can crack from the heat."),
                ("Let it cool", "After burning, leave the lantern to cool completely before moving it."),
                ("Dust the cutouts", "A soft brush clears dust from the pierced holes.")],
    "decor": [("Dust with a soft brush", "No water needed for a vase kept dry. For flowers, use a glass liner."),
              ("Not for hot liquids", "Vases are fired for beauty: they are not tested for sustained heat.")],
}

# key: (title, form, summary, story, firing, clay, glaze, colour, colour2, made, h, w, price, stock, featured, features, maker, bg, speckle, care)
PIECES = [
    dict(t="Ash Bowl No. 7", form="bowl", sum="A wide serving bowl with a warm, honeyed ash glaze that pools in the throwing rings.", story="<p>Seventh in a series Margo started after sweeping up the ash from the wood kiln one January. The glaze is wood ash, feldspar and a little bone ash, and it finds its own way down the wall of the bowl.</p><p>The inside is smooth enough for salad and the outside is rough enough to carry with wet hands.</p>", firing="wood", clay="stoneware", glaze="Wood ash over iron slip", c="#c9a15e", c2="#7a5030", made="2026-01-18", h=14, w=31, price=148, stock=True, feat=True, feats=["food_safe", "dishwasher_safe", "signed", "one_off"], maker="margo", bg="sand", speck=0.6),
    dict(t="Moonrise Noodle Bowl", form="bowl", sum="Deep, steep-sided and sized for a proper bowl of ramen.", story="<p>Tobias developed the pale blue glaze over two years of failed tiles. It breaks to a soft rust on every edge, which is why we call it moonrise.</p>", firing="reduction", clay="porcelain", glaze="Chun blue", c="#9eb6c9", c2="#eadfce", made="2026-02-04", h=10, w=19, price=46, stock=True, feat=False, feats=["food_safe", "dishwasher_safe", "microwave_safe"], maker="tobias", bg="sky", speck=0.1),
    dict(t="Tenmoku Serving Bowl", form="bowl", sum="Near-black iron glaze with a bronze rim. Substantial and very photogenic.", story="<p>Tenmoku is the glaze that looks black until the light catches it, and then it is every shade of brown. This bowl was thrown from nine pounds of clay and takes two hands.</p>", firing="reduction", clay="stoneware", glaze="Tenmoku", c="#3a2a22", c2="#b8793a", made="2025-11-30", h=16, w=34, price=165, stock=False, feat=False, feats=["food_safe", "signed"], maker="margo", bg="ink", speck=0.2),
    dict(t="Shino Fruit Bowl", form="bowl", sum="Carbon-trapped shino: a peach skin with grey flashes where the fire touched.", story="<p>Shino glazes trap smoke. Each fruit bowl carries a different pattern of grey where the flame licked the surface, so no two have the same face.</p>", firing="reduction", clay="stoneware", glaze="Carbon-trap shino", c="#e8a98a", c2="#6b6762", made="2026-02-20", h=12, w=28, price=92, stock=True, feat=False, feats=["food_safe", "one_off"], maker="odessa", bg="blush", speck=0.4),

    dict(t="Ember Vase", form="vase", sum="A tall vase with a rust-red body that darkens to charcoal at the neck.", story="<p>Thrown in two sections and joined while soft, a technique Margo learned from the old men in Shigaraki. The red is iron-rich slip; the black neck is manganese.</p><p>It holds a single branch like it was made for nothing else.</p>", firing="wood", clay="stoneware", glaze="Iron slip, manganese dip", c="#b5482a", c2="#2b2926", made="2026-01-09", h=42, w=24, price=240, stock=True, feat=True, feats=["one_off", "signed"], maker="margo", bg="sage", speck=0.3),
    dict(t="Bottle of Quiet Weather", form="vase", sum="A narrow-necked bottle in a grey-green glaze that changes with the light in the room.", story="<p>Named by Ines on the day she picked it from the kiln. It is the exact colour of a Welsh November morning.</p>", firing="reduction", clay="porcelain", glaze="Celadon, grey", c="#a9b8aa", c2=None, made="2026-03-02", h=34, w=16, price=118, stock=True, feat=False, feats=["one_off"], maker="ines", bg="sand", speck=0.1),
    dict(t="Tall Salt Vase", form="vase", sum="Salt-fired with the orange peel texture only salt gives.", story="<p>Odessa throws salt into the hot kiln at the peak of the firing. The sodium vaporises and coats everything in a pebbled skin. This vase came out of the front of the kiln, where the salt was heaviest.</p>", firing="salt", clay="stoneware", glaze="Salt vapour on iron", c="#d9a46a", c2="#8f5236", made="2025-12-14", h=45, w=20, price=210, stock=True, feat=False, feats=["one_off", "signed"], maker="odessa", bg="ochre", speck=0.5),

    dict(t="Morning Mug in Rust", form="mug", sum="The mug of the studio: heavy handle, wide mouth, glazed rust on the outside.", story="<p>Priya designed the handle after trying a hundred of them on a hundred hands. It is the only handle in the studio that fits a man with big hands and a child with small ones.</p>", firing="oxidation", clay="stoneware", glaze="Rust satin", c="#b5482a", c2="#e8dcc4", made="2026-03-10", h=10, w=11, price=34, stock=True, feat=True, feats=["dishwasher_safe", "microwave_safe", "food_safe"], maker="priya", bg="sand", speck=0.2),
    dict(t="Celadon Pour-over Mug", form="mug", sum="Sized to sit under a V60. Tall, slim, and a very calm green.", story="<p>Made for the pour-over crowd who kept using our mugs the wrong way up. The flat-ish rim supports a dripper and the cup holds exactly 350 ml.</p>", firing="reduction", clay="porcelain", glaze="Celadon", c="#8fb7a6", c2="#f3ecdf", made="2026-02-14", h=12, w=9, price=36, stock=True, feat=False, feats=["dishwasher_safe", "food_safe"], maker="tobias", bg="blush", speck=0.0),
    dict(t="Speckled Oat Mug", form="mug", sum="Our most popular mug, in a creamy glaze flecked with iron.", story="<p>Cream glaze, iron speckle, the colour of porridge with a little muscovado on top. Orders for this one arrive in fours and sixes.</p>", firing="oxidation", clay="stoneware", glaze="Oatmeal speckle", c="#e8dcc4", c2=None, made="2026-03-12", h=10, w=11, price=32, stock=True, feat=False, feats=["dishwasher_safe", "microwave_safe", "food_safe"], maker="ines", bg="sage", speck=1.0),
    dict(t="Indigo Handwarmer", form="mug", sum="A squat, wide mug designed to be held in both hands in January.", story="<p>Thrown thick-walled so that the heat from the tea stays put. Indigo glaze over a pale body, with the foot left raw.</p>", firing="oxidation", clay="stoneware", glaze="Indigo over white slip", c="#27406b", c2="#d6e4ec", made="2025-12-02", h=9, w=12, price=38, stock=False, feat=False, feats=["dishwasher_safe", "food_safe"], maker="ines", bg="sky", speck=0.0),

    dict(t="Kettle & Kin Teapot", form="teapot", sum="The studio's signature teapot: generous belly, three-cup pour, a lid that never falls out.", story="<p>Haruto asked for a teapot that could handle a Darjeeling and a pu-erh without keeping a flavour memory of either. The unglazed interior is bisque-fired porcelain; the outside wears Tobias's matte indigo.</p>", firing="reduction", clay="porcelain", glaze="Matte indigo", c="#27406b", c2="#e8dcc4", made="2026-02-27", h=17, w=22, price=128, stock=True, feat=True, feats=["food_safe", "signed"], maker="haruto", bg="sand", speck=0.4),
    dict(t="Hibiki Gaiwan Pot", form="teapot", sum="A small pot for gongfu tea: five cups, one hand, a lot of patience.", story="<p>Hibiki means resonance. Tap the lid against the pot and it rings. Haruto fires these himself, hot and fast, and rejects about a third of each batch.</p>", firing="reduction", clay="porcelain", glaze="Ash green", c="#6f8f6a", c2="#f3ecdf", made="2026-01-25", h=11, w=14, price=110, stock=True, feat=False, feats=["food_safe", "one_off"], maker="haruto", bg="sage", speck=0.2),

    dict(t="Supper Plate Set (Four)", form="plate", sum="Four generous supper plates in a dusky blue with a pale rim.", story="<p>Thrown in a single afternoon and dried together so the set shrinks evenly. The glaze is dipped twice for the pale rim, which catches the light on the table.</p>", firing="oxidation", clay="stoneware", glaze="Slate blue, oat rim", c="#5e7a9a", c2="#e8dcc4", made="2026-03-05", h=3, w=27, price=140, stock=True, feat=False, feats=["dishwasher_safe", "microwave_safe", "oven_safe", "food_safe"], maker="priya", bg="blush", speck=0.2),
    dict(t="Dune Cake Plate", form="plate", sum="A low, wide plate for cake, or for serving more than you meant to.", story="<p>Odessa pulled a piece of crumpled linen across the wet clay to make the dune texture. It looks hand-woven and feels like warm sand.</p>", firing="oxidation", clay="stoneware", glaze="Dune", c="#d9b99b", c2="#b8793a", made="2026-02-08", h=4, w=30, price=78, stock=True, feat=False, feats=["food_safe", "one_off"], maker="odessa", bg="ochre", speck=0.6),

    dict(t="Succulent Cradle", form="planter", sum="Shallow, wide and made for a handful of echeveria.", story="<p>Drainage hole, matching saucer, and enough clay weight to survive a cat. The glaze is honeyed mustard which looks wonderful against green.</p>", firing="oxidation", clay="terracotta", glaze="Mustard satin", c="#e0a526", c2="#c4572f", made="2026-03-08", h=14, w=22, price=42, stock=True, feat=False, feats=["food_safe"], maker="priya", bg="sky", speck=0.1, care="plant"),
    dict(t="Hanging Fern Pot", form="planter", sum="A planter with three lugs for a hanging cord. Fills a corner.", story="<p>The fern pot is among Priya's first hand-built designs for the studio. The glaze is a deep forest green with a darker dripped collar.</p>", firing="oxidation", clay="stoneware", glaze="Forest green", c="#3f6b4a", c2="#1f3a2a", made="2026-02-17", h=22, w=26, price=64, stock=True, feat=False, feats=["food_safe"], maker="priya", bg="sage", speck=0.3, care="plant"),
    dict(t="Windowsill Herb Pot", form="planter", sum="Terracotta, cheerfully orange, ready for your basil.", story="<p>We left the outside raw terracotta with a bright slip band round the top. It breathes, so herbs love it.</p>", firing="oxidation", clay="terracotta", glaze="Slip-banded terracotta", c="#c4572f", c2="#e8dcc4", made="2026-03-11", h=15, w=17, price=28, stock=True, feat=False, feats=["food_safe"], maker="dewi", bg="clay", speck=0.0, care="plant"),

    dict(t="Evening Star Lantern", form="lantern", sum="Pierced stars that throw a constellation across the wall.", story="<p>Each star is cut by hand with a hole punch while the clay is leather-hard. A tealight turns the whole room into a night sky. It is the piece we sell most at Christmas.</p>", firing="oxidation", clay="black_clay", glaze="Unglazed black clay", c="#38342f", c2=None, made="2025-11-20", h=28, w=17, price=96, stock=True, feat=True, feats=["one_off", "signed"], maker="priya", bg="dusk", speck=0.2, care="lantern"),
    dict(t="Hearth Lantern", form="lantern", sum="A heavier, squatter lantern in a warm smoked glaze.", story="<p>Made for the fireplace rather than the window. The glaze is a smoky brown that flickers like embers.</p>", firing="wood", clay="stoneware", glaze="Smoked brown", c="#6b3f2e", c2="#b8793a", made="2025-12-18", h=24, w=18, price=84, stock=True, feat=False, feats=["one_off"], maker="dewi", bg="ink", speck=0.4, care="lantern"),

    dict(t="Dawn Yunomi", form="tea_cup", sum="A tall cup for green tea, with a peach glaze that blushes at the rim.", story="<p>A yunomi is a tea cup without a handle, the sort you hold from underneath. Haruto chose the peach glaze so the green of a sencha looks even greener against the inside.</p>", firing="reduction", clay="porcelain", glaze="Peach blush", c="#e8a98a", c2="#f3ecdf", made="2026-03-01", h=9, w=8, price=26, stock=True, feat=False, feats=["food_safe", "dishwasher_safe"], maker="haruto", bg="blush", speck=0.0),
    dict(t="Harvest Tea Bowl", form="tea_cup", sum="A wide chawan for whisked tea, thick and warm to hold.", story="<p>The chawan is the one piece of tea ware that most rewards a great potter. This one belongs to the harvest series and wears a mottled amber glaze.</p>", firing="wood", clay="stoneware", glaze="Amber ash", c="#c98a3a", c2="#6b3f2e", made="2025-11-05", h=8, w=12, price=72, stock=True, feat=False, feats=["food_safe", "signed", "one_off"], maker="margo", bg="ochre", speck=0.4),
    dict(t="Cup of Small Hours", form="tea_cup", sum="A thumb-sized cup for strong, late-night tea. Midnight blue.", story="<p>Tiny, thick, and impossible to put down. We make them in sets of six.</p>", firing="reduction", clay="porcelain", glaze="Midnight blue", c="#1f2b4a", c2="#8fb7a6", made="2026-02-02", h=5, w=6, price=18, stock=True, feat=False, feats=["food_safe", "dishwasher_safe"], maker="tobias", bg="dusk", speck=0.2),

    dict(t="Heron Milk Jug", form="jug", sum="A small, long-necked jug with a pinched spout and a generous handle.", story="<p>It looks like a heron, standing still. The pour is clean and the handle sits low, so it feels light even when full.</p>", firing="oxidation", clay="stoneware", glaze="Grey heron", c="#aeb4b4", c2="#e8dcc4", made="2026-01-30", h=17, w=12, price=52, stock=True, feat=False, feats=["food_safe", "dishwasher_safe"], maker="ines", bg="sky", speck=0.2),
    dict(t="Orchard Ewer", form="jug", sum="A big-bellied water jug in apple-green glaze.", story="<p>Thrown to hold a litre and a half of water on the dinner table. The green is glaze number 112 in Tobias's lab book, nicknamed Granny Smith.</p>", firing="reduction", clay="stoneware", glaze="Apple green", c="#9db85a", c2="#e8dcc4", made="2026-02-23", h=24, w=19, price=84, stock=True, feat=False, feats=["food_safe", "one_off"], maker="odessa", bg="sage", speck=0.1),
]
